apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "myapp-136d"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "myapp-136d"
    spec:
      containers:
        - name: "myapp-136d"
          image: "myapplications.azurecr.io/myapp"
          ports:
          - containerPort: 80